name: Trigger Vercel Queue Worker

on:
  schedule:
    - cron: '*/1 * * * *'  # every 1 minutes;
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Queue Worker
        run: |
          curl -X POST https://omoolaex.com.ng/api/queue-worker \
          -H "x-worker-token: ${{ secrets.WORKER_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{}'
